# Generated by Django 4.0.3 on 2022-08-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QrGenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=15)),
            ],
        ),
    ]
