# Generated by Django 4.0.3 on 2022-08-12 21:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrgenmodel',
            name='color',
            field=colorfield.fields.ColorField(default='FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
