# Generated by Django 4.0.3 on 2022-08-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgen_app', '0002_alter_qrgenmodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrgenmodel',
            name='color',
            field=models.CharField(max_length=15),
        ),
    ]
