# Generated by Django 4.0.3 on 2022-08-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qruser_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSignUpModel',
        ),
    ]
