# Generated by Django 4.0.3 on 2022-08-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qruser_app', '0002_delete_usersignupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrSaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('qrname', models.CharField(max_length=100)),
                ('qrlink', models.CharField(max_length=150)),
            ],
        ),
    ]
