# Generated by Django 4.0.3 on 2022-08-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qruser_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QrSaver',
        ),
    ]
